version: "2"
formatters:
  enable:
    - gofumpt
    - goimports
linters:
  disable:
    - errcheck
    - staticcheck
  enable:
    - exhaustive
    - makezero
    - nakedret
    - prealloc
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign

run:
  go: "1.25"
  timeout: 10m
